# Generated by Django 2.1.5 on 2019-12-03 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('liked_number', models.IntegerField(blank=True, default=0, null=True)),
                ('reply_number', models.IntegerField(blank=True, default=0, null=True)),
                ('posted_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_head', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_text', models.TextField(blank=True, max_length=65535, null=True)),
                ('update_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('update_head', models.CharField(blank=True, max_length=255, null=True)),
                ('update_text', models.TextField(blank=True, max_length=65535, null=True)),
                ('note_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_note.NoteModel')),
                ('posted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='likemodel',
            name='note_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_note.NoteModel'),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='posted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
