# Generated by Django 2.1.5 on 2019-12-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_note', '0003_auto_20191215_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='en_img',
            new_name='posted_img',
        ),
        migrations.RenameField(
            model_name='notemodel',
            old_name='en_tag',
            new_name='posted_tag',
        ),
        migrations.RemoveField(
            model_name='notemodel',
            name='ja_img',
        ),
        migrations.RemoveField(
            model_name='notemodel',
            name='ja_tag',
        ),
    ]
