# Generated by Django 2.1.5 on 2019-12-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_note', '0006_notejsonmodel_note_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notejsonmodel',
            name='paper_json',
        ),
    ]
