# Generated by Django 2.1.5 on 2020-04-18 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_note', '0007_remove_notejsonmodel_paper_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('posted_head', models.CharField(blank=True, max_length=28, null=True)),
                ('posted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='notejsonmodel',
            name='note_object',
        ),
        migrations.RemoveField(
            model_name='notejsonmodel',
            name='posted_user',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='note_object',
        ),
        migrations.RemoveField(
            model_name='notemodel',
            name='en_head',
        ),
        migrations.RemoveField(
            model_name='notemodel',
            name='ja_head',
        ),
        migrations.RemoveField(
            model_name='notemodel',
            name='liked_number',
        ),
        migrations.RemoveField(
            model_name='notemodel',
            name='posted_img',
        ),
        migrations.RemoveField(
            model_name='notemodel',
            name='posted_tag',
        ),
        migrations.RemoveField(
            model_name='notemodel',
            name='reply_number',
        ),
        migrations.AddField(
            model_name='likemodel',
            name='like_number',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='notemodel',
            name='like_object',
            field=models.ManyToManyField(blank=True, related_name='note_object', to='app_note.LikeModel'),
        ),
        migrations.DeleteModel(
            name='NoteJSONModel',
        ),
        migrations.AddField(
            model_name='notemodel',
            name='tags_object',
            field=models.ManyToManyField(blank=True, related_name='note_object', to='app_note.TagsModel'),
        ),
    ]
