# Generated by Django 2.1.5 on 2020-04-23 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('like_number', models.CharField(blank=True, max_length=28, null=True)),
                ('posted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ja_text', models.TextField(blank=True, default='', max_length=65535, null=True)),
                ('en_text', models.TextField(blank=True, default='', max_length=65535, null=True)),
                ('like_object', models.ManyToManyField(blank=True, related_name='note_object', to='backend.LikeModel')),
                ('note_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.NoteModel')),
                ('posted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('posted_head', models.CharField(blank=True, max_length=28, null=True)),
                ('posted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notemodel',
            name='tags_object',
            field=models.ManyToManyField(blank=True, related_name='note_object', to='backend.TagsModel'),
        ),
    ]
