# Generated by Django 2.1.5 on 2019-12-02 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_indexjsonmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexjsonmodel',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
