# Generated by Django 2.1.5 on 2019-12-02 11:17

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_indexjsonmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexjsonmodel',
            name='segs',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
