// Auto-generated by https://github.com/react-spring/gltfjsx
// https://codesandbox.io/s/r3f-character-interaction-voef7?file=/src/Character.jsx:1209-1219
// import * as THREE from "three"
import React, {useRef} from "react"
import {useLoader} from "react-three-fiber"
import {GLTFLoader} from "three/examples/jsm/loaders/GLTFLoader"
const defaultURL =
   ["/static/core/FallGuyDefalti.glb",
    "/static/core/FallGuyDefalti.png"]
export const Motion = ({
    gltfURL=defaultURL[0],
    textureURL=defaultURL[1],
    dark=true, size=50, ...props
}) => {
    const group   = useRef<any>(null)
    // const actions = useRef<any>(null)
    // const mixer   = useMemo<any>(() => new THREE.AnimationMixer(undefined as any), [])
    // const texture = useLoader(THREE.TextureLoader, textureURL);
    const gltf    = useLoader<any>(GLTFLoader, gltfURL)
    return (
        <group ref={group} {...props} dispose={null}>
            <group scale={[1,1,1]} rotation={[0,.5,0]} position={[0,-1,-3]}>
                <primitive object={gltf.nodes["Scene"]} />
            </group>
        </group>
    )
}
//<primitive object={gltf.nodes["Scene"]} />
