# Generated by Django 2.1.5 on 2019-12-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='posted_img',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='notemodel',
            name='update_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
