# Generated by Django 2.1.5 on 2019-12-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_note', '0002_auto_20191208_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='posted_head',
            new_name='en_head',
        ),
        migrations.RenameField(
            model_name='notemodel',
            old_name='posted_tag',
            new_name='en_img',
        ),
        migrations.RenameField(
            model_name='notemodel',
            old_name='update_head',
            new_name='en_tag',
        ),
        migrations.RenameField(
            model_name='notemodel',
            old_name='posted_text',
            new_name='en_text',
        ),
        migrations.RenameField(
            model_name='notemodel',
            old_name='update_img',
            new_name='ja_head',
        ),
        migrations.RenameField(
            model_name='notemodel',
            old_name='posted_img',
            new_name='ja_img',
        ),
        migrations.RenameField(
            model_name='notemodel',
            old_name='update_tag',
            new_name='ja_tag',
        ),
        migrations.RenameField(
            model_name='notemodel',
            old_name='update_text',
            new_name='ja_text',
        ),
    ]
