# Generated by Django 2.1.5 on 2019-12-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_note', '0005_notejsonmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notejsonmodel',
            name='note_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_note.NoteModel'),
            preserve_default=False,
        ),
    ]
