# Generated by Django 2.1.5 on 2020-01-08 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSNSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('posted_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='en_text',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='ja_text',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='cardsnsmodel',
            name='card_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_card.CardModel'),
        ),
        migrations.AddField(
            model_name='cardsnsmodel',
            name='posted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
